<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <Summary>ScissorHands.Plugin.OpenGraph: Open Graph plugin for ScissorHands.NET</Summary>
    <Description>This is a library that uses Open Graph for ScissorHands.NET</Description>
    <PackageTags>scissorhands;plugin;static-site;open-graph</PackageTags>
  </PropertyGroup>

</Project>
