<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\sample\sample.csproj" />
    <Content Include="..\..\sample\contents\**\*"
             Link="SampleContents\%(RecursiveDir)%(Filename)%(Extension)"
             CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
